export const Env = {
  HOST: 'localhost',
  PORT: '8080',
  DB_NAME: 'Task_Management',
  USER_NAME: 'taskmanagementsystem',
  PASSWORD: '',
  DEV_URL: 'https://dev-tm.innovaturelabs.com/',
  IMG_URL: '/var/www/html/task-management-images/',
  FOLDER_PATH: '/var/www/html/task-management-data/',
  TASK_FILES: '/var/www/html/task-management-taskfiles/',
  GET_IMAGE_URL: 'https://dev-tm-images.innovaturelabs.com/',
  GET_TASK_FILE_URL: 'https://dev-tm-taskfiles.innovaturelabs.com/',
  URL: 'https://dev-tm.innovaturelabs.com/',
  ACCESS_TOKEN_EXPIRY: '5h',
  REFRESH_TOKEN_EXPIRY: '1d',
  FORGOT_PASSWORD_TOKEN_EXPIRY: '5m',
  // HOST: 'localhost',
  // PORT: '8080',
  // DB_NAME: 'dump',
  // USER_NAME: 'root',
  // PASSWORD: 'Innovature@123',
  // DEV_URL: 'https://dev-tm.innovaturelabs.com/',
  // IMG_URL: '/var/www/html/task-management-images/',
  // FOLDER_PATH: '/var/www/html/task-management-data/',
  // TASK_FILES: '/var/www/html/task-management-taskfiles/',
  // GET_IMAGE_URL: 'https://dev-tm-images.innovaturelabs.com/',
  // GET_TASK_FILE_URL: 'https://dev-tm-taskfiles.innovaturelabs.com/',
  // URL: 'https://dev-tm.innovaturelabs.com/',
  // ACCESS_TOKEN_EXPIRY: '5h',
  // REFRESH_TOKEN_EXPIRY: '1d',
  // FORGOT_PASSWORD_TOKEN_EXPIRY: '5m',
};
